"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { AnalysisResult, FinancialInput } from "@/lib/types";

type Row = { id:number; company_name:string; ticker:string; date:string; data_json:string; score:number; recommendation:string; source:string };
type Item = Record<string, any>;
const tabs = ["Analyze", "Trends", "Watchlist", "Alerts", "History", "CSE Reports"];
const numeric = ["revenue","revenue_prev","net_income","net_income_prev","eps","eps_prev","total_assets","total_equity","total_liabilities","current_assets","current_liabilities","market_price","shares_outstanding","dividend_per_share","operating_cash_flow"] as const;
const empty: FinancialInput = { company_name:"",ticker:"",fiscal_year:new Date().getFullYear().toString(),report_type:"annual",revenue:0,revenue_prev:0,net_income:0,net_income_prev:0,eps:0,eps_prev:0,total_assets:0,total_equity:0,total_liabilities:0,current_assets:0,current_liabilities:0,market_price:0,shares_outstanding:0,dividend_per_share:0,operating_cash_flow:0 };
const labels: Record<string,string> = { revenue:"Revenue (M)",revenue_prev:"Previous revenue (M)",net_income:"Net income (M)",net_income_prev:"Previous net income (M)",eps:"EPS",eps_prev:"Previous EPS",total_assets:"Total assets (M)",total_equity:"Total equity (M)",total_liabilities:"Total liabilities (M)",current_assets:"Current assets (M)",current_liabilities:"Current liabilities (M)",market_price:"Market price (LKR)",shares_outstanding:"Shares outstanding (M)",dividend_per_share:"Dividend / share",operating_cash_flow:"Operating cash flow (M)" };

export default function Dashboard({ username }: { username:string }) {
  const [tab,setTab]=useState("Analyze"), [data,setData]=useState<{history:Row[];watchlist:Item[];alerts:Item[]}>({history:[],watchlist:[],alerts:[]});
  const [form,setForm]=useState<FinancialInput>(empty), [result,setResult]=useState<AnalysisResult|null>(null), [message,setMessage]=useState(""), [busy,setBusy]=useState(false);
  async function refresh(){const r=await fetch("/api/data");if(r.ok)setData(await r.json());}
  useEffect(()=>{refresh()},[]);
  async function logout(){await fetch("/api/auth",{method:"DELETE"});location.reload()}
  async function extract(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("Reading the report with AI…");const fd=new FormData(e.currentTarget);const r=await fetch("/api/extract",{method:"POST",body:fd});const j=await r.json();setBusy(false);if(!r.ok)return setMessage(j.error);setForm({...empty,...j.data});setMessage("Extraction complete. Review the figures, then score the company.")}
  async function analyze(e:FormEvent){e.preventDefault();setBusy(true);const r=await fetch("/api/analysis",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();setBusy(false);if(!r.ok)return setMessage(j.error);setResult(j.analysis);setMessage("Analysis saved to your shared database.");await refresh()}
  async function action(url:string,method:string,body:unknown){await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});await refresh()}
  return <div className="shell"><aside><div className="brand small"><span>G</span> Graham Pro</div><nav>{tabs.map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}><i>{({Analyze:"⌁",Trends:"↗",Watchlist:"☆",Alerts:"◉",History:"◷","CSE Reports":"▤"} as any)[t]}</i>{t}</button>)}</nav><div className="user"><div>{username.slice(0,1).toUpperCase()}</div><span><b>{username}</b><small>Investor workspace</small></span><button onClick={logout} title="Sign out">↪</button></div></aside><main className="dashboard"><header><div><p className="eyebrow">GRAHAM PRO / {tab.toUpperCase()}</p><h1>{tab === "Analyze" ? "Financial analysis" : tab}</h1></div><div className="live"><span/> DATABASE CONNECTED</div></header>
  {tab==="Analyze"&&<><section className="hero"><div><p className="eyebrow">REPORT TO DECISION</p><h2>Find the signal inside<br/>the financial statements.</h2><p>Upload a report for AI extraction, review the numbers, and apply Benjamin Graham’s discipline.</p></div><form onSubmit={extract} className="upload"><input required name="file" type="file" accept="application/pdf"/><button className="primary" disabled={busy}>Extract report</button><small>PDF · Maximum 14 MB · Processed securely</small></form></section>{message&&<div className="notice">{message}</div>}<AnalysisForm form={form} setForm={setForm} submit={analyze} busy={busy}/>{result&&<Result result={result} watch={()=>action("/api/watchlist","POST",{ticker:result.ticker,company_name:result.company_name})}/>}</>}
  {tab==="History"&&<History rows={data.history} select={(r)=>{const d=JSON.parse(r.data_json);setResult(d._analysis||null);setTab("Analyze")}}/>}
  {tab==="Watchlist"&&<Watchlist items={data.watchlist} history={data.history} remove={(ticker)=>action("/api/watchlist","DELETE",{ticker})}/>}
  {tab==="Alerts"&&<Alerts items={data.alerts} history={data.history} add={(v)=>action("/api/alerts","POST",v)} remove={(id)=>action("/api/alerts","DELETE",{id})}/>}
  {tab==="Trends"&&<Trends rows={data.history}/>}
  {tab==="CSE Reports"&&<Empty title="Automated CSE reports" text="The existing Python pipeline can continue collecting CSE announcements into this same database. New automatic analyses appear here and across trends, history, and watchlists without a second migration."/>}
  </main></div>;
}

function AnalysisForm({form,setForm,submit,busy}:{form:FinancialInput;setForm:(v:FinancialInput)=>void;submit:(e:FormEvent)=>void;busy:boolean}){
 const edit=(k:string,v:string)=>setForm({...form,[k]:numeric.includes(k as any)?Number(v):v});
 return <form onSubmit={submit} className="panel form"><div className="section-title"><div><p className="eyebrow">VERIFIED INPUTS</p><h3>Review financial data</h3></div><span>All totals in LKR millions</span></div><div className="grid identity"><label>Company name<input required value={form.company_name} onChange={e=>edit("company_name",e.target.value)}/></label><label>Ticker<input required value={form.ticker} onChange={e=>edit("ticker",e.target.value.toUpperCase())}/></label><label>Fiscal year<input value={form.fiscal_year} onChange={e=>edit("fiscal_year",e.target.value)}/></label><label>Report type<select value={form.report_type} onChange={e=>edit("report_type",e.target.value)}><option value="annual">Annual</option><option value="quarterly">Quarterly</option></select></label></div><div className="grid fields">{numeric.map(k=><label key={k}>{labels[k]}<input type="number" step="any" value={form[k]} onChange={e=>edit(k,e.target.value)}/></label>)}</div><button className="primary score" disabled={busy}>Calculate & save analysis <span>→</span></button></form>
}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><b>{value}</b></div>}
function Result({result:r,watch}:{result:AnalysisResult;watch:()=>void}){const f=(v:number|null,d=1,s="")=>v==null?"N/A":`${v.toFixed(d)}${s}`;return <section className="results"><div className={`grade grade-${r.graham_grade}`}><div><span>GRAHAM GRADE</span><b>{r.graham_grade}</b></div><div><p>{r.company_name} · {r.ticker}</p><h2>{r.recommendation}</h2><small>{r.graham_score}/15 quality score</small></div><button onClick={watch}>☆ Add to watchlist</button></div><div className="metrics"><Metric label="Intrinsic value" value={`LKR ${f(r.intrinsic_value,2)}`}/><Metric label="Market price" value={`LKR ${f(r.market_price,2)}`}/><Metric label="Margin of safety" value={f(r.mos_pct,1,"%")}/><Metric label="Max buy price" value={`LKR ${f(r.max_buy_price,2)}`}/></div><div className="result-grid"><div className="panel"><h3>Fundamental ratios</h3><div className="ratio-grid"><Metric label="P/E" value={f(r.pe)}/><Metric label="P/B" value={f(r.pb,2)}/><Metric label="ROE" value={f(r.roe_calc,1,"%")}/><Metric label="Current ratio" value={f(r.current_ratio,2)}/><Metric label="Debt / equity" value={f(r.de,2)}/><Metric label="Dividend yield" value={f(r.div_yield,1,"%")}/></div></div><div className="panel decision"><p className="eyebrow">DECISION</p><h3>{r.buy_decision}</h3><p>{r.bottom_line}</p><div><b>{r.allocation_pct}%</b><span>suggested maximum allocation</span></div></div></div><div className="panel"><h3>Graham scorecard</h3><div className="score-table">{r.score_table.map((x,i)=><div key={i}><span>{x.criterion}<small>{x.value}</small></span><div><i style={{width:`${x.points/x.max*100}%`}}/></div><b>{x.points}/{x.max}</b></div>)}</div></div></section>}
function History({rows,select}:{rows:Row[];select:(r:Row)=>void}){return <section className="panel table"><div className="section-title"><div><p className="eyebrow">RESEARCH LEDGER</p><h3>Saved analyses</h3></div><span>{rows.length} records</span></div>{rows.length?<table><thead><tr><th>Date</th><th>Company</th><th>Ticker</th><th>Score</th><th>Signal</th><th>Source</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} onClick={()=>select(r)}><td>{r.date}</td><td>{r.company_name}</td><td><b>{r.ticker}</b></td><td>{r.score}/15</td><td><span className="pill">{r.recommendation}</span></td><td>{r.source||"manual"}</td></tr>)}</tbody></table>:<Empty title="No analyses yet" text="Analyze your first report to start the ledger."/>}</section>}
function Watchlist({items,history,remove}:{items:Item[];history:Row[];remove:(t:string)=>void}){return <section><div className="cards">{items.map(x=>{const latest=history.find(h=>h.ticker===x.ticker);return <article className="stock" key={x.id}><button onClick={()=>remove(x.ticker)}>×</button><p className="eyebrow">{x.ticker}</p><h3>{x.company_name}</h3><div><b>{latest?`${latest.score}/15`:"—"}</b><span>Graham score</span></div><footer>{latest?.recommendation||"Awaiting analysis"}<small>Added {x.added_date}</small></footer></article>})}</div>{!items.length&&<Empty title="Your watchlist is clear" text="Add a company from any completed analysis."/>}</section>}
function Alerts({items,history,add,remove}:{items:Item[];history:Row[];add:(v:unknown)=>void;remove:(id:number)=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const ticker=String(f.get("ticker"));const h=history.find(x=>x.ticker===ticker);add({ticker,company_name:h?.company_name||ticker,alert_type:f.get("type"),threshold:f.get("threshold"),email:f.get("email")});e.currentTarget.reset()}return <><form className="panel alert-form" onSubmit={submit}><div><p className="eyebrow">NEW RULE</p><h3>Create an investment alert</h3></div><label>Ticker<select name="ticker" required>{[...new Set(history.map(h=>h.ticker))].map(t=><option key={t}>{t}</option>)}</select></label><label>Condition<select name="type"><option value="score_above">Score rises above</option><option value="score_below">Score falls below</option><option value="mos_above">Margin of safety above</option><option value="price_below">Price below</option></select></label><label>Threshold<input name="threshold" required type="number" step="any"/></label><label>Email<input name="email" required type="email"/></label><button className="primary">Save alert</button></form><div className="cards">{items.map(a=><article className="stock" key={a.id}><button onClick={()=>remove(a.id)}>×</button><p className="eyebrow">ACTIVE RULE</p><h3>{a.ticker} · {String(a.alert_type).replaceAll("_"," ")}</h3><div><b>{a.threshold}</b><span>trigger threshold</span></div><footer>{a.email}<small>{a.last_triggered?`Last sent ${a.last_triggered}`:"Not triggered yet"}</small></footer></article>)}</div></>}
function Trends({rows}:{rows:Row[]}){const tickers=[...new Set(rows.map(r=>r.ticker))];const [ticker,setTicker]=useState(tickers[0]||"");const points=useMemo(()=>rows.filter(r=>r.ticker===ticker).map(r=>{try{const d=JSON.parse(r.data_json);return {year:d.fiscal_year||r.date.slice(0,4),score:r.score,revenue:Number(d.revenue)||0,eps:Number(d.eps)||0}}catch{return null}}).filter(Boolean).reverse(),[rows,ticker]);return <section className="panel"><div className="section-title"><div><p className="eyebrow">LONG-TERM VIEW</p><h3>Fundamental trend</h3></div><select value={ticker} onChange={e=>setTicker(e.target.value)}>{tickers.map(t=><option key={t}>{t}</option>)}</select></div>{points.length?<div className="chart"><ResponsiveContainer width="100%" height={360}><AreaChart data={points}><defs><linearGradient id="gold" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#b88a44" stopOpacity={.35}/><stop offset="95%" stopColor="#b88a44" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="year"/><YAxis domain={[0,15]}/><Tooltip/><Area type="monotone" dataKey="score" stroke="#b88a44" fill="url(#gold)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div>:<Empty title="Not enough history" text="Saved reports for a ticker will build its long-term trend."/>}</section>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><span>◇</span><h3>{title}</h3><p>{text}</p></div>}
